<?php

namespace App\Http\Middleware;

use Carbon\CarbonInterval;
use Closure;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Http\Exceptions\ThrottleRequestsException;

class ThrottleRequests extends \Illuminate\Routing\Middleware\ThrottleRequests
{
    public function handle($request, Closure $next, $maxAttempts = 60, $decayMinutes = 1, $prefix = '')
    {
        if (config('app.bypass_throttle')) {
            return $next($request);
        }

        return parent::handle($request, $next, $maxAttempts, $decayMinutes, $prefix); // TODO: Change the autogenerated stub
    }

    protected function buildException($request, $key, $maxAttempts, $responseCallback = null): HttpResponseException|ThrottleRequestsException
    {
        //time in seconds
        $retryAfter = $this->getTimeUntilNextRetry($key);

        $headers = $this->getHeaders(
            $maxAttempts,
            $this->calculateRemainingAttempts($key, $maxAttempts, $retryAfter),
            $retryAfter
        );

        //use carbon to format the time to minutes under 60 minutes or hours over 60 minutes
        $retryAfter = CarbonInterval::seconds($retryAfter)
            ->ceilMinute()
            ->forHumans([
                'parts' => 1,
            ]);

        return is_callable($responseCallback)
            ? new HttpResponseException($responseCallback($request, $headers))
            : new ThrottleRequestsException(__('throttle.too-many-attempts', ['retry_after' => $retryAfter]), null, $headers);
    }
}
